### ISSUE TITLE
可以提供训练方法和命令吗，对于LADAN+MTL

### ISSUE THREAD

**Issue by hecongqing** [prometheusXN/D-LADAN#2]

**Comment by hecongqing** [comment]
LADAN+TOPJUDGE
LADAN+MPBFN

这两个变体的脚本你可以参考 DLADAN_model.py里面的代码进行配置，目前LADAN_model.py中只实现了LADAN+MTL的tensorflow2.x版本，但是对于DLADAN模型，MTL、TOPJUDGE、MPBFN三种decoder的配置都是实现了的，可以参考着修改。

**Comment by prometheusXN** [comment]
![image](https://github.com/prometheusXN/D-LADAN/assets/22512477/456758c0-87d7-4be4-88ea-98a8ce7e3fe4)
这个图片不是写了你需要调用的脚本么？我不是很明确你需要什么样子的命令？

**Comment by hecongqing** [comment]
比如 python  train_DLADAN.py   Ladan.config  可以得到 LADAN的效果？

怎么搭配config文件没有解释， 如果方便的话，可否简单说明下

**Comment by prometheusXN** [comment]
![image](https://github.com/prometheusXN/D-LADAN/assets/22512477/1aba1f7e-9073-4ee0-ab01-715da3bba99f)
直接替换代码里面的路径即可，自己可以查阅一下代码，后续我们会修改，谢谢提醒
